### ISSUE TITLE
use of analogRead crashes emulator

### ISSUE THREAD

**Issue by maniflames** [hapiel/3L1B#2]
```cpp
analogRead(0);
```

crashes the emulator: expected fix is init of all analog ports.

**Comment by maniflames** [comment]
Emulation of analogRead not supported out of the box. Solution found in [wokwi/avr8js issue #13](https://github.com/wokwi/avr8js/issues/13). Should be fixed by [#bc9d7c](https://github.com/hapiel/3L1B/commit/c8b614705600844d17c45ccdd2c5748098cfa806).

**Comment by urish** [comment]
Note: we now have proper ADC support (beta) in the [adc branch](https://github.com/wokwi/avr8js/tree/adc/src). It'll probably be released in a couple of weeks, after some testing.
